#!/usr/intel/pkgs/python3/3.6.3a/modules/r1/bin/python  -B
#from __future__ import unicode_literals
from htd_unix_socket import *


client = htd_unix_socket_client(12)

print(client.send_receive_message(("#Dror Remark Line ")))
print(client.send_receive_message(("#initialize val:  ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.gl2saVccSTPwrGoodXnnnH 0 ")))
print(client.send_receive_message(("rem: peek_signal soc_tb.gl2pcRawPwrGoodXnnnH 0 ")))
print(client.send_receive_message(("#rem: peek_signal soc_tb.gl2sarstbRnnnH 1     ")))
print(client.send_receive_message(("rem: peek_signal soc_tb.gl2sapcunoadebugFXnn2H[15:0]  0 ")))
print(client.send_receive_message(("rem: peek_signal soc_tb.gl2sapcunoadebugbXnn1L[13:12]  0")))
print(client.send_receive_message(("rem: peek_signal soc_tb.fuse_sense_done 0")))
print(client.send_receive_message(("rem: peek_signal soc_tb.early_boot_done 0")))
print(client.send_receive_message(("#phase 0 val:                            ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.gl2saEarXnnnH 1 ")))
print(client.send_receive_message(("rem: peek_signal soc_tb.gl2sarstbRnnnH 0 ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.gl2saVccSTPwrGoodXnnnH 1 ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.gl2sapcunoadebugFXnn2H[15:0] 0xff9f #CFG.get_hex(\"NOA_STRAP\"): ")))
print(client.send_receive_message(("rem: peek_signal soc_tb.gl2sapcunoadebugbXnn1L[13:12] 0x3   #CFG.get(\"PMSYNC_LEGACY_MODE_EN\");")))
print(client.send_receive_message(("#phase 1a val:	                        ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.gl2pcRawPwrGoodXnnnH 1 ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.fuse_sense_done 1")))
print(client.send_receive_message(("rem: poll_signal soc_tb.early_boot_done 1")))
print(client.send_receive_message(("rem: deposit_signal soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.mltadregs.tap_core.U2CPma_CoreConfigRestartUXnnnH 1")))
print(client.send_receive_message(("#rem: deposit_signal soc_tb.soc.par_core1.cnlcore1clnt_wrap.cnlcore1clnt.core.meu.mlc.mltadregs.tap_core.U2CPma_CoreConfigRestartUXnnnH 1")))
print(client.send_receive_message(("rem: poll_signal soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.mltadregs.tap_core.ConfigRestartMXnnnH 1")))
print(client.send_receive_message(("#rem: poll_signal soc_tb.soc.par_core1.cnlcore1clnt_wrap.cnlcore1clnt.core.meu.mlc.mltadregs.tap_core.ConfigRestartMXnnnH 1")))
print(client.send_receive_message(("#phase 1b val:")))
print(client.send_receive_message(("rem: poll_signal soc_tb.gl2sarstbRnnnH 1 ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.gl2sapcunoadebugFXnn2H[15:0] 0 ")))
print(client.send_receive_message(("rem: peek_signal soc_tb.gl2sapcunoadebugbXnn1L[13:12]  0 #if CFG.get(\"PMSYNC_LEGACY_MODE_EN\"); ")))
print(client.send_receive_message(("#loading ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.soc.par_punit.punit.pcuctrls.ptpcioregs.io_gdxc_msg_typeU702H.msg_type[7:0] 0xa0 #wait for pcode slow loop ")))
print(client.send_receive_message(("#mlc invalidation:	")))
print(client.send_receive_message(("rem: deposit_signal  soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.mlprefc.ccbwrdataM310H[3:0] 0x9 ")))
print(client.send_receive_message(("rem: deposit_signal  soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.mlprefc.CRCacheRstWrEnM310H 1	  ")))
print(client.send_receive_message(("#rem: deposit_signal  soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.mlprefc.ml6cregM3nnH.cache_reset.flush_spc_cyc[4:0] 0x9  #mlc invalidation	")))
print(client.send_receive_message(("# wait 3 Mclk	                                                                                                   ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.Mclk 1	                           ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.Mclk 0	                           ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.Mclk 1	                           ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.Mclk 0	                           ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.Mclk 1	                           ")))
print(client.send_receive_message(("rem: poll_signal soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.Mclk 0	                           ")))
print(client.send_receive_message(("rem: deposit_signal  soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.mlprefc.ccbwrdataM310H[3:0] 0x0  ")))
print(client.send_receive_message(("rem: deposit_signal  soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.mlprefc.CRCacheRstWrEnM310H 0 ")))
print(client.send_receive_message(("#wait 4 mlc_invalidation	                                                                                         ")))
print(client.send_receive_message(("rem: poll_signal      soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.mlprefc.ml6cregM3nnH.cache_reset.mlc_reset_done 1       #wait 4 mlc_invalidation	")))
print(client.send_receive_message(("rem: deposit_signal  soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.mlprefc.ml6cregM3nnH.cache_reset.flush_spc_cyc[4:0] 0x0  #mlc invalidation	")))
print(client.send_receive_message(("#Load:	                                                                                                                                                                ")))
print(client.send_receive_message(("rem: deposit_signal   soc_tb.hvm_sbft_ti.hvm_sbft_env_if.cache_reset 1                       # load obj file     	")))
print(client.send_receive_message(("rem: poll_signal      soc_tb.hvm_sbft_ti.hvm_sbft_env_if.cache_reset  0                     # wait for load to end	")))
print(client.send_receive_message(("#rem: deposit_signal   soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.allocator 1 #allocator stall	")))
print(client.send_receive_message(("rem: deposit_signal   soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.mltadregs.mltaAlStall0M735H   1 #allocator stall	")))
print(client.send_receive_message(("# wait bclk")))
print(client.send_receive_message(("rem: poll_signal soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.Bclk 1")))
print(client.send_receive_message(("rem: poll_signal soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.Bclk 0")))
print(client.send_receive_message(("# core reset")))
print(client.send_receive_message(("rem: deposit_signal   soc_tb.soc.par_core0.cnlcore0clnt_wrap.cnlcore0clnt.core.meu.mlc.mltadregs.GQ2MLCoreResetUW000L 0")))
